In [137]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [138]:
df = pd.read_csv('/Users/rahul/Desktop/GDSC-ML Tasks/New Dataset/WA_Fn-UseC_-Telco-Customer-Churn.csv')
pd.set_option('display.max_columns', None)
df.head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No
7,6713-OKOMC,Female,0,No,No,10,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,No,Mailed check,29.75,301.9,No
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,No,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
9,6388-TABGU,Male,0,No,Yes,62,Yes,No,DSL,Yes,Yes,No,No,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,No

In [139]:
# Yes/No - SeniorCitizen, Partner, Dependents, PhoneService, PaperlessBilling, Churn -->convert to 1s and 0s
#Yes/No/No internet service - OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies -->OneHotEncode
#Yes/No/No phone service - MultipleLines -->OneHotEncode
#Categorical Ordinal - Contract -->LabelEncode
#Categorical Nominal - Gender, Payment Method, InternetService --> OneHotEncode
#int64 - tenure, MonthlyCharges, TotalCharges --> keep as it is
#Drop - customerId --> Drop as its not necessary

In [140]:
df.shape

(7043, 21)

In [141]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [142]:
for column in df.columns:
    val_counts = df[column].value_counts()
    print(f"Column: {column}")
    print(f"Unique values: {val_counts}")
    print("\n")

Column: customerID
Unique values: customerID
7590-VHVEG    1
3791-LGQCY    1
6008-NAIXK    1
5956-YHHRX    1
5365-LLFYV    1
             ..
9796-MVYXX    1
2637-FKFSY    1
1552-AAGRX    1
4304-TSPVK    1
3186-AJIEK    1
Name: count, Length: 7043, dtype: int64


Column: gender
Unique values: gender
Male      3555
Female    3488
Name: count, dtype: int64


Column: SeniorCitizen
Unique values: SeniorCitizen
0    5901
1    1142
Name: count, dtype: int64


Column: Partner
Unique values: Partner
No     3641
Yes    3402
Name: count, dtype: int64


Column: Dependents
Unique values: Dependents
No     4933
Yes    2110
Name: count, dtype: int64


Column: tenure
Unique values: tenure
1     613
72    362
2     238
3     200
4     176
     ...
28     57
39     56
44     51
36     50
0      11
Name: count, Length: 73, dtype: int64


Column: PhoneService
Unique values: PhoneService
Yes    6361
No      682
Name: count, dtype: int64


Column: MultipleLines
Unique values: MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64


Column: InternetService
Unique values: InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64


Column: OnlineSecurity
Unique values: OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64


Column: OnlineBackup
Unique values: OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64


Column: DeviceProtection
Unique values: DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64


Column: TechSupport
Unique values: TechSupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64


Column: StreamingTV
Unique values: StreamingTV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64


Column: StreamingMovies
Unique values: StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64


Column: Contract
Unique values: Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64


Column: PaperlessBilling
Unique values: PaperlessBilling
Yes    4171
No     2872
Name: count, dtype: int64


Column: PaymentMethod
Unique values: PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64


Column: MonthlyCharges
Unique values: MonthlyCharges
20.05     61
19.85     45
19.95     44
19.90     44
20.00     43
          ..
23.65      1
114.70     1
43.65      1
87.80      1
78.70      1
Name: count, Length: 1585, dtype: int64


Column: TotalCharges
Unique values: TotalCharges
          11
20.2      11
19.75      9
20.05      8
19.9       8
          ..
6849.4     1
692.35     1
130.15     1
3211.9     1
6844.5     1
Name: count, Length: 6531, dtype: int64


Column: Churn
Unique values: Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [143]:
df.customerID.nunique()

7043

In [144]:
df.tenure.unique()

array([ 1, 34,  2, 45,  8, 22, 10, 28, 62, 13, 16, 58, 49, 25, 69, 52, 71,
       21, 12, 30, 47, 72, 17, 27,  5, 46, 11, 70, 63, 43, 15, 60, 18, 66,
        9,  3, 31, 50, 64, 56,  7, 42, 35, 48, 29, 65, 38, 68, 32, 55, 37,
       36, 41,  6,  4, 33, 67, 23, 57, 61, 14, 20, 53, 40, 59, 24, 44, 19,
       54, 51, 26,  0, 39])

In [145]:
df.TotalCharges.dtype

dtype('O')

In [146]:
df.MonthlyCharges.nunique()

1585

In [147]:
df.loc[df['TotalCharges']==' ']

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [148]:
df1 = df.copy()

In [149]:
#Handle missing values in TotalCharges
df1['TotalCharges'] = df1['TotalCharges'].replace(' ', np.nan)
df1['TotalCharges'] = pd.to_numeric(df1['TotalCharges'], errors='coerce')
df1['TotalCharges'] = df1['TotalCharges'].fillna(df1['TotalCharges'].median())

In [150]:
print(df1['TotalCharges'].dtype)
print(df1['TotalCharges'].isnull().sum())

float64
0

In [151]:
print(df1['MonthlyCharges'].dtype)
print(df1['tenure'].dtype)
print(df1['MonthlyCharges'].isnull().sum())
print(df1['tenure'].isnull().sum())

float64
int64
0
0

In [152]:
# Yes/No - SeniorCitizen, Partner, Dependents, PhoneService, PaperlessBilling, Churn -->convert to 1s and 0s
#Yes/No/No internet service - OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies -->OneHotEncode
#Yes/No/No phone service - MultipleLines -->OneHotEncode
#Categorical Ordinal - Contract -->LabelEncode
#Categorical Nominal - Gender, Payment Method, InternetService --> OneHotEncode
#int64 - tenure, MonthlyCharges, TotalCharges --> keep as it is
#Drop - customerId --> Drop as its not necessary

In [153]:
binary_columns = ['SeniorCitizen', 'Partner', 'Dependents', 'PhoneService', 'PaperlessBilling', 'Churn']
#Replacing the Yes and Nos to 1s and 0s
df1[binary_columns] = df1[binary_columns].replace({'Yes': 1, 'No': 0})

/var/folders/q6/0pfb75k55856k8_ms3tldx240000gn/T/ipykernel_3151/950828846.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1[binary_columns] = df1[binary_columns].replace({'Yes': 1, 'No': 0})

In [154]:
#Drop unnecessary columns:
df1.drop(columns=['customerID'], inplace =True)

In [155]:
#Label Encoding the contract column:
from sklearn.preprocessing import LabelEncoder

# Initialize the LabelEncoder
le = LabelEncoder()

# Fit and transform the 'Contract' column
df1['Contract'] = le.fit_transform(df1['Contract'])

# Check the encoded values
print(df1['Contract'].unique())

[0 1 2]

In [156]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Define the columns to OneHotEncode
columns_to_encode = ['OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 
                     'StreamingTV', 'StreamingMovies', 'MultipleLines', 
                     'gender', 'PaymentMethod', 'InternetService']

# Initialize the OneHotEncoder
ohe = OneHotEncoder(sparse_output=False)

# Create a ColumnTransformer to apply OneHotEncoder to the specified columns
column_transformer = ColumnTransformer(
    transformers=[('ohe', ohe, columns_to_encode)], remainder='passthrough')

# Fit and transform the data
df_encoded = column_transformer.fit_transform(df1)

# Retrieve the feature names after fitting
encoded_columns = column_transformer.named_transformers_['ohe'].get_feature_names_out(columns_to_encode)

# Convert the transformed data back to a DataFrame with the correct column names
df_encoded = pd.DataFrame(df_encoded, columns= df1.drop(columns_to_encode, axis=1).columns.tolist() + list(encoded_columns))

# Check the encoded DataFrame
df_encoded.head()

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,Contract,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,OnlineSecurity_No,OnlineSecurity_No internet service,OnlineSecurity_Yes,OnlineBackup_No,OnlineBackup_No internet service,OnlineBackup_Yes,DeviceProtection_No,DeviceProtection_No internet service,DeviceProtection_Yes,TechSupport_No,TechSupport_No internet service,TechSupport_Yes,StreamingTV_No,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No,StreamingMovies_No internet service,StreamingMovies_Yes,MultipleLines_No,MultipleLines_No phone service,MultipleLines_Yes,gender_Female,gender_Male,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,InternetService_DSL,InternetService_Fiber optic,InternetService_No
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,29.85,29.85,0.0
1,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,34.0,1.0,1.0,0.0,56.95,1889.50,0.0
2,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,1.0,53.85,108.15,1.0
3,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,45.0,0.0,1.0,0.0,42.30,1840.75,0.0
4,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,1.0,70.70,151.65,1.0

In [157]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [158]:
encoded_columns

array(['OnlineSecurity_No', 'OnlineSecurity_No internet service',
       'OnlineSecurity_Yes', 'OnlineBackup_No',
       'OnlineBackup_No internet service', 'OnlineBackup_Yes',
       'DeviceProtection_No', 'DeviceProtection_No internet service',
       'DeviceProtection_Yes', 'TechSupport_No',
       'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No', 'StreamingTV_No internet service',
       'StreamingTV_Yes', 'StreamingMovies_No',
       'StreamingMovies_No internet service', 'StreamingMovies_Yes',
       'MultipleLines_No', 'MultipleLines_No phone service',
       'MultipleLines_Yes', 'gender_Female', 'gender_Male',
       'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No'], dtype=object)

In [159]:
df_encoded.shape

(7043, 40)

In [160]:
for column in df_encoded.columns:
    val_counts = df_encoded[column].value_counts()
    print(f"Column: {column}")
    print(f"Unique values: {val_counts}")
    print("\n")

Column: SeniorCitizen
Unique values: SeniorCitizen
0.0    3545
1.0    3498
Name: count, dtype: int64


Column: Partner
Unique values: Partner
0.0    5517
1.0    1526
Name: count, dtype: int64


Column: Dependents
Unique values: Dependents
0.0    5024
1.0    2019
Name: count, dtype: int64


Column: tenure
Unique values: tenure
0.0    3955
1.0    3088
Name: count, dtype: int64


Column: PhoneService
Unique values: PhoneService
0.0    5517
1.0    1526
Name: count, dtype: int64


Column: Contract
Unique values: Contract
0.0    4614
1.0    2429
Name: count, dtype: int64


Column: PaperlessBilling
Unique values: PaperlessBilling
0.0    3948
1.0    3095
Name: count, dtype: int64


Column: MonthlyCharges
Unique values: MonthlyCharges
0.0    5517
1.0    1526
Name: count, dtype: int64


Column: TotalCharges
Unique values: TotalCharges
0.0    4621
1.0    2422
Name: count, dtype: int64


Column: Churn
Unique values: Churn
0.0    3570
1.0    3473
Name: count, dtype: int64


Column: OnlineSecurity_No
Unique values: OnlineSecurity_No
0.0    5517
1.0    1526
Name: count, dtype: int64


Column: OnlineSecurity_No internet service
Unique values: OnlineSecurity_No internet service
0.0    4999
1.0    2044
Name: count, dtype: int64


Column: OnlineSecurity_Yes
Unique values: OnlineSecurity_Yes
0.0    4233
1.0    2810
Name: count, dtype: int64


Column: OnlineBackup_No
Unique values: OnlineBackup_No
0.0    5517
1.0    1526
Name: count, dtype: int64


Column: OnlineBackup_No internet service
Unique values: OnlineBackup_No internet service
0.0    4336
1.0    2707
Name: count, dtype: int64


Column: OnlineBackup_Yes
Unique values: OnlineBackup_Yes
0.0    4258
1.0    2785
Name: count, dtype: int64


Column: DeviceProtection_No
Unique values: DeviceProtection_No
0.0    5517
1.0    1526
Name: count, dtype: int64


Column: DeviceProtection_No internet service
Unique values: DeviceProtection_No internet service
0.0    4311
1.0    2732
Name: count, dtype: int64


Column: DeviceProtection_Yes
Unique values: DeviceProtection_Yes
0.0    3653
1.0    3390
Name: count, dtype: int64


Column: TechSupport_No
Unique values: TechSupport_No
0.0    6361
1.0     682
Name: count, dtype: int64


Column: TechSupport_No internet service
Unique values: TechSupport_No internet service
0.0    4072
1.0    2971
Name: count, dtype: int64


Column: TechSupport_Yes
Unique values: TechSupport_Yes
0.0    3555
1.0    3488
Name: count, dtype: int64


Column: StreamingTV_No
Unique values: StreamingTV_No
1.0    3555
0.0    3488
Name: count, dtype: int64


Column: StreamingTV_No internet service
Unique values: StreamingTV_No internet service
0.0    5499
1.0    1544
Name: count, dtype: int64


Column: StreamingTV_Yes
Unique values: StreamingTV_Yes
0.0    5521
1.0    1522
Name: count, dtype: int64


Column: StreamingMovies_No
Unique values: StreamingMovies_No
0.0    4678
1.0    2365
Name: count, dtype: int64


Column: StreamingMovies_No internet service
Unique values: StreamingMovies_No internet service
0.0    5431
1.0    1612
Name: count, dtype: int64


Column: StreamingMovies_Yes
Unique values: StreamingMovies_Yes
0.0    4622
1.0    2421
Name: count, dtype: int64


Column: MultipleLines_No
Unique values: MultipleLines_No
0.0    3947
1.0    3096
Name: count, dtype: int64


Column: MultipleLines_No phone service
Unique values: MultipleLines_No phone service
0.0    5517
1.0    1526
Name: count, dtype: int64


Column: MultipleLines_Yes
Unique values: MultipleLines_Yes
0.0    5901
1.0    1142
Name: count, dtype: int64


Column: gender_Female
Unique values: gender_Female
0.0    3641
1.0    3402
Name: count, dtype: int64


Column: gender_Male
Unique values: gender_Male
0.0    4933
1.0    2110
Name: count, dtype: int64


Column: PaymentMethod_Bank transfer (automatic)
Unique values: PaymentMethod_Bank transfer (automatic)
1.0     613
72.0    362
2.0     238
3.0     200
4.0     176
       ...
28.0     57
39.0     56
44.0     51
36.0     50
0.0      11
Name: count, Length: 73, dtype: int64


Column: PaymentMethod_Credit card (automatic)
Unique values: PaymentMethod_Credit card (automatic)
1.0    6361
0.0     682
Name: count, dtype: int64


Column: PaymentMethod_Electronic check
Unique values: PaymentMethod_Electronic check
0.0    3875
2.0    1695
1.0    1473
Name: count, dtype: int64


Column: PaymentMethod_Mailed check
Unique values: PaymentMethod_Mailed check
1.0    4171
0.0    2872
Name: count, dtype: int64


Column: InternetService_DSL
Unique values: InternetService_DSL
20.05     61
19.85     45
19.95     44
19.90     44
20.00     43
          ..
23.65      1
114.70     1
43.65      1
87.80      1
78.70      1
Name: count, Length: 1585, dtype: int64


Column: InternetService_Fiber optic
Unique values: InternetService_Fiber optic
1397.475    11
20.200      11
19.750       9
20.050       8
19.900       8
            ..
6849.400     1
692.350      1
130.150      1
3211.900     1
6844.500     1
Name: count, Length: 6531, dtype: int64


Column: InternetService_No
Unique values: InternetService_No
0.0    5174
1.0    1869
Name: count, dtype: int64